name: Update NCAA Data

concurrency:
  group: update-ncaa-data
  cancel-in-progress: true

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

     - name: Commit updated dataset
       run: |
   	 git config user.name "github-actions"
    	 git config user.email "github-actions@github.com"

    	 git add data/ncaa_womens_lacrosse_team_stats_2026.csv

    	 git commit -m "Auto update NCAA stats" || echo "No changes"

   	 git push --force-with-lease https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main